"""task_log_retry_count

Revision ID: abdd29045842
Revises: c22a5c9d5c22
Create Date: 2026-03-15 05:38:04.655449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abdd29045842'
down_revision: Union[str, None] = 'c22a5c9d5c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('background_task_logs', sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('background_task_logs', 'retry_count')
    # ### end Alembic commands ###
