"""chatbot auto_detect_language

Revision ID: 578bc93711ac
Revises: a3f7c1d9e24b
Create Date: 2026-03-15 05:24:22.882053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '578bc93711ac'
down_revision: Union[str, None] = 'a3f7c1d9e24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('auto_detect_language', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbots', 'auto_detect_language')
    # ### end Alembic commands ###
