"""add qa_pairs table

Revision ID: 225457a90aa5
Revises: 20260313_intel
Create Date: 2026-03-13 20:31:01.076353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '225457a90aa5'
down_revision: Union[str, None] = '20260313_intel'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_pairs',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('chatbot_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('suggested_answer', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('kb_document_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kb_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_pairs_chatbot_id'), 'qa_pairs', ['chatbot_id'], unique=False)
    op.create_index(op.f('ix_qa_pairs_workspace_id'), 'qa_pairs', ['workspace_id'], unique=False)
    op.drop_index(op.f('idx_action_events_chatbot'), table_name='action_events')
    op.drop_index(op.f('idx_action_events_conversation'), table_name='action_events')
    op.drop_index(op.f('idx_action_events_workspace'), table_name='action_events')
    op.alter_column('article_collections', 'collection_type',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'collection'::text"))
    op.alter_column('article_collections', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('articles', 'state',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'draft'::text"))
    op.alter_column('articles', 'is_ai_drafted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('articles', 'views_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('articles', 'helpful_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('articles', 'not_helpful_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('articles', 'language',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'en'::text"))
    op.alter_column('articles', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_chatbot_actions_chatbot'), table_name='chatbot_actions')
    op.drop_index(op.f('idx_chatbot_actions_workspace'), table_name='chatbot_actions')
    op.alter_column('chatbots', 'display_name',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'Assistant'::text"))
    op.alter_column('chatbots', 'tone',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'professional'::text"))
    op.alter_column('chatbots', 'language',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'en'::text"))
    op.alter_column('chatbots', 'llm_provider',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'openai'::text"))
    op.alter_column('chatbots', 'llm_model',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'gpt-4o-mini'::text"))
    op.alter_column('chatbots', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.3'))
    op.alter_column('chatbots', 'max_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1000'))
    op.alter_column('chatbots', 'confidence_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.65'))
    op.alter_column('chatbots', 'retrieval_top_k',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
    op.alter_column('chatbots', 'use_reranking',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('chatbots', 'use_hybrid_retrieval',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('chatbots', 'fallback_type',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'escalate'::text"))
    op.alter_column('chatbots', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('chatbots', 'widget_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('chunks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_chunks_embedding'), table_name='chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('idx_chunks_embedding_hnsw'), table_name='chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_chunks_fts'), table_name='chunks', postgresql_using='gin')
    op.alter_column('companies', 'custom_attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('contact_events', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('contacts', 'contact_type',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'visitor'::text"))
    op.alter_column('contacts', 'lifecycle_stage',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'unknown'::text"))
    op.alter_column('contacts', 'lead_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('contacts', 'custom_attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('conversation_analysis', 'llm_model',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'gpt-4o-mini'::text"))
    op.alter_column('conversation_tags', 'applied_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'open'::text"))
    op.alter_column('conversations', 'priority',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'normal'::text"))
    op.alter_column('conversations', 'channel',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'chat'::text"))
    op.alter_column('conversations', 'lifecycle_stage',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'unknown'::text"))
    op.alter_column('conversations', 'ai_participated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('conversations', 'autonomous_resolved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('conversations', 'stats',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_conversations_country_code'), table_name='conversations')
    op.drop_index(op.f('idx_crawl_jobs_kb_id'), table_name='crawl_jobs')
    op.drop_constraint(op.f('crawl_jobs_kb_id_fkey'), 'crawl_jobs', type_='foreignkey')
    op.drop_constraint(op.f('crawl_jobs_workspace_id_fkey'), 'crawl_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'crawl_jobs', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key(None, 'crawl_jobs', 'knowledge_bases', ['kb_id'], ['id'])
    op.drop_index(op.f('idx_credit_ledger_workspace'), table_name='credit_ledger')
    op.alter_column('data_attributes', 'archived',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('documents', 'status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('documents', 'chunk_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('documents', 'sync_frequency',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'weekly'::text"))
    op.alter_column('documents', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_documents_content_hash'), table_name='documents', postgresql_where='(content_hash IS NOT NULL)')
    op.drop_index(op.f('idx_documents_kb_status'), table_name='documents')
    op.alter_column('gap_clusters', 'gap_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('gap_clusters', 'status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'open'::text"))
    op.alter_column('gap_clusters', 'clustered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('fk_gap_events_gap_cluster_id'), 'gap_events', type_='foreignkey')
    op.create_foreign_key(None, 'gap_events', 'gap_clusters', ['gap_cluster_id'], ['id'])
    op.alter_column('integration_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('idx_integration_configs_workspace'), table_name='integration_configs')
    op.alter_column('knowledge_bases', 'kb_type',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'general'::text"))
    op.alter_column('message_feedback', 'rating',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index(op.f('ix_message_feedback_message_id'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_workspace_id'), table_name='message_feedback')
    op.alter_column('messages', 'content_type',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'text'::text"))
    op.alter_column('messages', 'attachments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('messages', 'status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'sent'::text"))
    op.alter_column('messages', 'is_fallback',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('retrieval_logs', 'reranked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('retrieval_logs', 'escalated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('retrieval_logs', 'response_generated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('segments', 'person_type',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'contact'::text"))
    op.alter_column('tags', 'color',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'#6366f1'::text"))
    op.drop_index(op.f('ix_workspace_webhooks_workspace_id'), table_name='workspace_webhooks')
    op.alter_column('workspaces', 'plan',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'free'::text"))
    op.alter_column('workspaces', 'plan_conversation_cap',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('workspaces', 'timezone',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'UTC'::text"))
    op.alter_column('workspaces', 'primary_language',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'en'::text"))
    op.alter_column('workspaces', 'onboarding_step',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('workspaces', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('workspaces', 'credit_balance',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1000'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'credit_balance',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1000'))
    op.alter_column('workspaces', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('workspaces', 'onboarding_step',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('workspaces', 'primary_language',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'en'::text"))
    op.alter_column('workspaces', 'timezone',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'UTC'::text"))
    op.alter_column('workspaces', 'plan_conversation_cap',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.alter_column('workspaces', 'plan',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'free'::text"))
    op.create_index(op.f('ix_workspace_webhooks_workspace_id'), 'workspace_webhooks', ['workspace_id'], unique=False)
    op.alter_column('tags', 'color',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'#6366f1'::text"))
    op.alter_column('segments', 'person_type',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'contact'::text"))
    op.alter_column('retrieval_logs', 'response_generated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('retrieval_logs', 'escalated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('retrieval_logs', 'reranked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('messages', 'is_fallback',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('messages', 'status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'sent'::text"))
    op.alter_column('messages', 'attachments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('messages', 'content_type',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'text'::text"))
    op.create_index(op.f('ix_message_feedback_workspace_id'), 'message_feedback', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_message_feedback_message_id'), 'message_feedback', ['message_id'], unique=False)
    op.alter_column('message_feedback', 'rating',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'kb_type',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'general'::text"))
    op.create_index(op.f('idx_integration_configs_workspace'), 'integration_configs', ['workspace_id'], unique=False)
    op.alter_column('integration_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'gap_events', type_='foreignkey')
    op.create_foreign_key(op.f('fk_gap_events_gap_cluster_id'), 'gap_events', 'gap_clusters', ['gap_cluster_id'], ['id'], ondelete='SET NULL')
    op.alter_column('gap_clusters', 'clustered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('gap_clusters', 'status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'open'::text"))
    op.alter_column('gap_clusters', 'gap_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('idx_documents_kb_status'), 'documents', ['knowledge_base_id', 'status'], unique=False)
    op.create_index(op.f('idx_documents_content_hash'), 'documents', ['content_hash'], unique=False, postgresql_where='(content_hash IS NOT NULL)')
    op.alter_column('documents', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('documents', 'sync_frequency',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'weekly'::text"))
    op.alter_column('documents', 'chunk_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('documents', 'status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('data_attributes', 'archived',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('idx_credit_ledger_workspace'), 'credit_ledger', ['workspace_id'], unique=False)
    op.drop_constraint(None, 'crawl_jobs', type_='foreignkey')
    op.drop_constraint(None, 'crawl_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('crawl_jobs_workspace_id_fkey'), 'crawl_jobs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('crawl_jobs_kb_id_fkey'), 'crawl_jobs', 'knowledge_bases', ['kb_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_crawl_jobs_kb_id'), 'crawl_jobs', ['kb_id'], unique=False)
    op.create_index(op.f('ix_conversations_country_code'), 'conversations', ['country_code'], unique=False)
    op.alter_column('conversations', 'stats',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('conversations', 'autonomous_resolved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('conversations', 'ai_participated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('conversations', 'lifecycle_stage',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'unknown'::text"))
    op.alter_column('conversations', 'channel',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'chat'::text"))
    op.alter_column('conversations', 'priority',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'normal'::text"))
    op.alter_column('conversations', 'status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'open'::text"))
    op.alter_column('conversation_tags', 'applied_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversation_analysis', 'llm_model',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'gpt-4o-mini'::text"))
    op.alter_column('contacts', 'custom_attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('contacts', 'lead_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('contacts', 'lifecycle_stage',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'unknown'::text"))
    op.alter_column('contacts', 'contact_type',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'visitor'::text"))
    op.alter_column('contact_events', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('companies', 'custom_attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index(op.f('idx_chunks_fts'), 'chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_chunks_embedding_hnsw'), 'chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_chunks_embedding'), 'chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('chunks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('chatbots', 'widget_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('chatbots', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('chatbots', 'fallback_type',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'escalate'::text"))
    op.alter_column('chatbots', 'use_hybrid_retrieval',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('chatbots', 'use_reranking',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('chatbots', 'retrieval_top_k',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
    op.alter_column('chatbots', 'confidence_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.65'))
    op.alter_column('chatbots', 'max_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1000'))
    op.alter_column('chatbots', 'temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.3'))
    op.alter_column('chatbots', 'llm_model',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'gpt-4o-mini'::text"))
    op.alter_column('chatbots', 'llm_provider',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'openai'::text"))
    op.alter_column('chatbots', 'language',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'en'::text"))
    op.alter_column('chatbots', 'tone',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'professional'::text"))
    op.alter_column('chatbots', 'display_name',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'Assistant'::text"))
    op.create_index(op.f('idx_chatbot_actions_workspace'), 'chatbot_actions', ['workspace_id'], unique=False)
    op.create_index(op.f('idx_chatbot_actions_chatbot'), 'chatbot_actions', ['chatbot_id'], unique=False)
    op.alter_column('articles', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('articles', 'language',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'en'::text"))
    op.alter_column('articles', 'not_helpful_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('articles', 'helpful_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('articles', 'views_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('articles', 'is_ai_drafted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('articles', 'state',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'draft'::text"))
    op.alter_column('article_collections', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('article_collections', 'collection_type',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'collection'::text"))
    op.create_index(op.f('idx_action_events_workspace'), 'action_events', ['workspace_id'], unique=False)
    op.create_index(op.f('idx_action_events_conversation'), 'action_events', ['conversation_id'], unique=False)
    op.create_index(op.f('idx_action_events_chatbot'), 'action_events', ['chatbot_id'], unique=False)
    op.drop_index(op.f('ix_qa_pairs_workspace_id'), table_name='qa_pairs')
    op.drop_index(op.f('ix_qa_pairs_chatbot_id'), table_name='qa_pairs')
    op.drop_table('qa_pairs')
    # ### end Alembic commands ###
