"""add default_chatbot_model to workspaces

Revision ID: 3faba4c3c07e
Revises: d58d952084a2
Create Date: 2026-03-16 06:43:57.279164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3faba4c3c07e'
down_revision: Union[str, None] = 'd58d952084a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('default_chatbot_model', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'default_chatbot_model')
    # ### end Alembic commands ###
