"""add setup_error to chatbots

Revision ID: 63e7f147b8c4
Revises: 3faba4c3c07e
Create Date: 2026-03-16 08:34:41.716095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63e7f147b8c4'
down_revision: Union[str, None] = '3faba4c3c07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('setup_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbots', 'setup_error')
    # ### end Alembic commands ###
