"""add workspace internal_model

Revision ID: ba95cbd3f658
Revises: e8cdd201a0cc
Create Date: 2026-03-14 11:04:48.567236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba95cbd3f658'
down_revision: Union[str, None] = 'e8cdd201a0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('internal_model', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'internal_model')
    # ### end Alembic commands ###
