"""add openrouter_base_url to workspaces

Revision ID: c568c7ff8d42
Revises: 225457a90aa5
Create Date: 2026-03-14 07:23:41.166494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c568c7ff8d42'
down_revision: Union[str, None] = '225457a90aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('openrouter_base_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'openrouter_base_url')
    # ### end Alembic commands ###
