"""add plan_tiers table and workspace is_byok

Revision ID: d58d952084a2
Revises: abdd29045842
Create Date: 2026-03-15 07:02:00.814346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd58d952084a2'
down_revision: Union[str, None] = 'abdd29045842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_tiers',
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('price_monthly_cents', sa.Integer(), nullable=False),
    sa.Column('max_chatbots', sa.Integer(), nullable=False),
    sa.Column('max_conversations_monthly', sa.Integer(), nullable=False),
    sa.Column('max_knowledge_bases', sa.Integer(), nullable=False),
    sa.Column('max_chars_indexed', sa.BigInteger(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.add_column('workspaces', sa.Column('is_byok', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    # ### end Alembic commands ###

    # Seed plan tiers
    op.execute("""
        INSERT INTO plan_tiers (slug, name, price_monthly_cents, max_chatbots, max_conversations_monthly, max_knowledge_bases, max_chars_indexed, features, created_at)
        VALUES
            ('free', 'Free', 0, 1, 100, 2, 500000, '[]', NOW()),
            ('starter', 'Starter', 4900, 3, 1000, 10, 2000000, '["email_reports"]', NOW()),
            ('growth', 'Growth', 14900, 10, 10000, 50, 10000000, '["intelligence", "reranking", "email_reports"]', NOW()),
            ('professional', 'Professional', 14900, 10, 10000, 50, 10000000, '["intelligence", "reranking", "email_reports"]', NOW()),
            ('agency', 'Agency', 49900, 50, 50000, 200, -1, '["intelligence", "reranking", "email_reports"]', NOW()),
            ('enterprise', 'Enterprise', 0, -1, -1, -1, -1, '["intelligence", "reranking", "email_reports", "priority_support"]', NOW())
        ON CONFLICT (slug) DO NOTHING
    """)

    # Normalize professional -> growth
    op.execute("UPDATE workspaces SET plan = 'growth' WHERE plan = 'professional'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'is_byok')
    op.drop_table('plan_tiers')
    # ### end Alembic commands ###
