"""add background_task_logs table

Revision ID: e8cdd201a0cc
Revises: 9187fe5ac70d
Create Date: 2026-03-14 10:42:46.522696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8cdd201a0cc'
down_revision: Union[str, None] = '9187fe5ac70d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_task_logs',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('task_name', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_task_logs_task_id'), 'background_task_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_background_task_logs_task_name'), 'background_task_logs', ['task_name'], unique=False)
    op.create_index(op.f('ix_background_task_logs_workspace_id'), 'background_task_logs', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_background_task_logs_workspace_id'), table_name='background_task_logs')
    op.drop_index(op.f('ix_background_task_logs_task_name'), table_name='background_task_logs')
    op.drop_index(op.f('ix_background_task_logs_task_id'), table_name='background_task_logs')
    op.drop_table('background_task_logs')
    # ### end Alembic commands ###
